#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  GLITCH IN MATRIX — MASTER DEPLOYMENT ORCHESTRATOR                         ║
# ║  Engineered by ФорексГод                                                    ║
# ║                                                                             ║
# ║  One-Click VPS Deployment: Environment → Filesystem → Services → Health     ║
# ║  Version: V8.0 VPS-Ready Edition                                           ║
# ║  Protocol: deploy_glitch.sh → vps_env_setup.py → watchdog_monitor.py       ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
set -euo pipefail

# ─── COLORS & SYMBOLS ───────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
WHITE='\033[1;37m'
DIM='\033[2m'
BOLD='\033[1m'
NC='\033[0m'

OK="${GREEN}✅${NC}"
FAIL="${RED}❌${NC}"
WARN="${YELLOW}⚠️${NC}"
ARROW="${CYAN}▸${NC}"
GEAR="${MAGENTA}⚙️${NC}"

# ─── GLOBAL VARS ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${SCRIPT_DIR}/.venv"
PYTHON="${VENV_DIR}/bin/python"
PIP="${VENV_DIR}/bin/pip"
LOG_DIR="${SCRIPT_DIR}/logs"
DEPLOY_LOG="${LOG_DIR}/deploy_$(date -u +%Y%m%d_%H%M%S).log"
REQUIREMENTS="${SCRIPT_DIR}/requirements_vps.txt"

# Force UTC globally
export TZ=UTC

# ─── BANNER ─────────────────────────────────────────────────────────────────
banner() {
    echo ""
    echo -e "${GREEN}"
    cat << 'BANNER'
     ██████╗ ██╗     ██╗████████╗ ██████╗██╗  ██╗
    ██╔════╝ ██║     ██║╚══██╔══╝██╔════╝██║  ██║
    ██║  ███╗██║     ██║   ██║   ██║     ███████║
    ██║   ██║██║     ██║   ██║   ██║     ██╔══██║
    ╚██████╔╝███████╗██║   ██║   ╚██████╗██║  ██║
     ╚═════╝ ╚══════╝╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝
BANNER
    echo -e "${NC}"
    echo -e "${WHITE}${BOLD}    I N   M A T R I X${NC}"
    echo -e "${DIM}    Engineered by${NC} ${GREEN}${BOLD}ФорексГод${NC}"
    echo -e "${DIM}    ─────────────────────────────────────${NC}"
    echo -e "${DIM}    VPS Deployment Orchestrator V8.0${NC}"
    echo -e "${DIM}    $(date -u '+%Y-%m-%d %H:%M:%S UTC')${NC}"
    echo ""
}

# ─── LOGGING ─────────────────────────────────────────────────────────────────
mkdir -p "${LOG_DIR}"

log() {
    local level="$1"; shift
    local msg="$*"
    local ts
    ts=$(date -u '+%Y-%m-%d %H:%M:%S')
    echo "[${ts}] [${level}] ${msg}" >> "${DEPLOY_LOG}"
    case "${level}" in
        OK)    echo -e "  ${OK}  ${msg}" ;;
        FAIL)  echo -e "  ${FAIL}  ${msg}" ;;
        WARN)  echo -e "  ${WARN}  ${msg}" ;;
        INFO)  echo -e "  ${ARROW}  ${msg}" ;;
        STEP)  echo -e "\n${GEAR}  ${WHITE}${BOLD}${msg}${NC}" ;;
    esac
}

# ─── ERROR HANDLER ──────────────────────────────────────────────────────────
trap_handler() {
    local exit_code=$?
    if [[ ${exit_code} -ne 0 ]]; then
        echo ""
        log FAIL "Deployment failed at line $1 with exit code ${exit_code}"
        log FAIL "Check deploy log: ${DEPLOY_LOG}"
        echo -e "\n  ${RED}${BOLD}╔═══════════════════════════════════════════╗${NC}"
        echo -e "  ${RED}${BOLD}║  DEPLOYMENT FAILED — CHECK LOGS           ║${NC}"
        echo -e "  ${RED}${BOLD}╚═══════════════════════════════════════════╝${NC}\n"
        exit ${exit_code}
    fi
}
trap 'trap_handler ${LINENO}' ERR

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1: ENVIRONMENT CHECK
# ═══════════════════════════════════════════════════════════════════════════════
phase_environment() {
    log STEP "PHASE 1/5 — ENVIRONMENT CHECK"

    # 1a. Detect OS
    local os_type
    os_type="$(uname -s)"
    log INFO "OS Detected: ${os_type} ($(uname -m))"

    # 1b. Check Python
    if [[ ! -f "${PYTHON}" ]]; then
        log WARN "Virtual environment not found at ${VENV_DIR}"
        log INFO "Creating virtual environment..."
        python3 -m venv "${VENV_DIR}" 2>>"${DEPLOY_LOG}"
        log OK "Virtual environment created"
    else
        local py_ver
        py_ver=$("${PYTHON}" --version 2>&1)
        log OK "Python: ${py_ver} (${PYTHON})"
    fi

    # 1c. Generate requirements_vps.txt
    log INFO "Generating production requirements..."
    cat > "${REQUIREMENTS}" << 'REQS'
# ╔══════════════════════════════════════════════════════════════════╗
# ║  GLITCH IN MATRIX — VPS Production Dependencies                ║
# ║  Generated by deploy_glitch.sh                                 ║
# ║  Engineered by ФорексГод                                        ║
# ╚══════════════════════════════════════════════════════════════════╝

# === CORE DATA SCIENCE ===
numpy>=1.26.0
pandas>=2.1.0
scikit-learn>=1.3.0

# === BROKER & MARKET DATA ===
requests>=2.31.0
python-dotenv>=1.0.0

# === LOGGING & MONITORING ===
loguru>=0.7.0
psutil>=5.9.0
schedule>=1.2.0

# === TELEGRAM BOT ===
python-telegram-bot==20.7

# === CHARTING ===
matplotlib>=3.8.0
mplfinance>=0.12.0

# === WEB INTERFACE ===
flask>=3.0.0
flask-cors>=4.0.0

# === VALIDATION ===
pydantic>=2.5.0

# === FILE WATCHING ===
watchdog>=3.0.0
REQS
    log OK "requirements_vps.txt generated (17 packages)"

    # 1d. Install dependencies
    log INFO "Installing dependencies (pip install -r requirements_vps.txt)..."
    "${PIP}" install --upgrade pip >> "${DEPLOY_LOG}" 2>&1
    "${PIP}" install -r "${REQUIREMENTS}" >> "${DEPLOY_LOG}" 2>&1
    log OK "All dependencies installed"

    # 1e. Verify critical imports
    log INFO "Verifying critical imports..."
    "${PYTHON}" -c "
import pandas, numpy, loguru, requests, psutil, schedule, dotenv, flask
print('ALL_IMPORTS_OK')
" 2>>"${DEPLOY_LOG}" | grep -q "ALL_IMPORTS_OK"
    log OK "Critical imports verified: pandas, numpy, loguru, requests, psutil, schedule"
}

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2: FILESYSTEM ARCHITECTURE
# ═══════════════════════════════════════════════════════════════════════════════
phase_filesystem() {
    log STEP "PHASE 2/5 — FILESYSTEM ARCHITECTURE"

    # Required directories
    local dirs=(
        "${SCRIPT_DIR}/logs"
        "${SCRIPT_DIR}/data"
        "${SCRIPT_DIR}/backups"
        "${SCRIPT_DIR}/charts"
        "${SCRIPT_DIR}/chart_snapshots"
        "${SCRIPT_DIR}/archive"
    )

    for dir in "${dirs[@]}"; do
        mkdir -p "${dir}"
        log OK "Directory: $(basename "${dir}")/"
    done

    # Apollo permission — ensure cTrader can read/write signals.json
    log INFO "Setting permissions for cTrader IPC bridge..."
    chmod 777 "${SCRIPT_DIR}" 2>/dev/null || true
    # Ensure signals.json is accessible
    touch "${SCRIPT_DIR}/signals.json" 2>/dev/null || true
    chmod 666 "${SCRIPT_DIR}/signals.json" 2>/dev/null || true
    log OK "Apollo directory: chmod 777 (cTrader IPC bridge ready)"

    # Ensure critical state files exist
    local state_files=(
        "monitoring_setups.json"
        "signals.json"
        "active_positions.json"
        "trade_confirmations.json"
    )

    for sf in "${state_files[@]}"; do
        local fpath="${SCRIPT_DIR}/${sf}"
        if [[ ! -f "${fpath}" ]]; then
            echo "[]" > "${fpath}"
            log WARN "Created missing state file: ${sf} (initialized as [])"
        else
            log OK "State file exists: ${sf} ($(wc -c < "${fpath}" | tr -d ' ')B)"
        fi
    done

    # .env check
    if [[ -f "${SCRIPT_DIR}/.env" ]]; then
        local env_keys
        env_keys=$(grep -c "=" "${SCRIPT_DIR}/.env" 2>/dev/null || echo "0")
        log OK ".env file: ${env_keys} keys configured"
    else
        log FAIL ".env file not found! Telegram & cTrader will not work."
        log INFO "Create .env with: TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, CTRADER_*"
        return 1
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 3: GLOBAL UTC SYNC
# ═══════════════════════════════════════════════════════════════════════════════
phase_timezone() {
    log STEP "PHASE 3/5 — GLOBAL UTC SYNC"

    # Verify TZ=UTC is forced in all critical Python files
    local critical_files=(
        "setup_executor_monitor.py"
        "position_monitor.py"
        "watchdog_monitor.py"
        "realtime_monitor.py"
        "telegram_command_center.py"
        "ctrader_executor.py"
        "daily_scanner.py"
    )

    local tz_count=0
    for cf in "${critical_files[@]}"; do
        if grep -q "os.environ\['TZ'\]" "${SCRIPT_DIR}/${cf}" 2>/dev/null; then
            tz_count=$((tz_count + 1))
        else
            log WARN "TZ=UTC NOT forced in: ${cf}"
        fi
    done

    log OK "TZ=UTC enforcement: ${tz_count}/${#critical_files[@]} Python processes"

    # Runtime verification (uses datetime.timezone.utc for cross-platform reliability)
    local tz_test
    tz_test=$("${PYTHON}" -c "
import os, time
os.environ['TZ'] = 'UTC'
try:
    time.tzset()
except AttributeError:
    pass
from datetime import datetime, timezone
utc_now = datetime.now(timezone.utc)
local_now = datetime.now()
drift = abs((utc_now.replace(tzinfo=None) - local_now).total_seconds())
tz_label = 'UTC' if drift < 2 else f'DRIFT_{drift:.0f}s'
print(f'{tz_label}|{utc_now.strftime(\"%Y-%m-%d %H:%M:%S\")} UTC')
" 2>/dev/null)

    local tz_zone
    tz_zone=$(echo "${tz_test}" | cut -d'|' -f1)
    local tz_time
    tz_time=$(echo "${tz_test}" | cut -d'|' -f2)

    if [[ "${tz_zone}" == "UTC" ]]; then
        log OK "Runtime TZ verification: ${tz_zone} — ${tz_time}"
    else
        log FAIL "TZ verification failed: got '${tz_zone}' — local time drifts from UTC"
        return 1
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 4: WATCHDOG TRIGGER
# ═══════════════════════════════════════════════════════════════════════════════
phase_watchdog() {
    log STEP "PHASE 4/5 — WATCHDOG TRIGGER"

    # Verify all subsystem scripts exist
    local subsystems=(
        "watchdog_monitor.py"
        "setup_executor_monitor.py"
        "position_monitor.py"
        "realtime_monitor.py"
        "telegram_command_center.py"
        "ctrader_sync_daemon.py"
        "news_calendar_monitor.py"
        "daily_scanner.py"
    )

    local missing=0
    for sub in "${subsystems[@]}"; do
        if [[ -f "${SCRIPT_DIR}/${sub}" ]]; then
            log OK "Subsystem present: ${sub}"
        else
            log FAIL "MISSING subsystem: ${sub}"
            missing=$((missing + 1))
        fi
    done

    if [[ ${missing} -gt 0 ]]; then
        log FAIL "${missing} subsystem(s) missing — cannot proceed"
        return 1
    fi

    # Verify loguru file logging is configured in watchdog
    if grep -q "logger.add" "${SCRIPT_DIR}/watchdog_monitor.py" 2>/dev/null; then
        log OK "Watchdog: loguru file rotation configured"
    else
        log WARN "Watchdog: loguru file logging NOT detected"
    fi

    # Verify watchdog stdout/stderr redirect (not DEVNULL)
    if grep -q "stdout_log\|stderr_log" "${SCRIPT_DIR}/watchdog_monitor.py" 2>/dev/null; then
        log OK "Watchdog: stdout/stderr → forensic log files"
    else
        log WARN "Watchdog: may still use DEVNULL for subprocess output"
    fi

    # Syntax-check all subsystems before launching
    log INFO "Syntax-checking all subsystems..."
    local syntax_ok=0
    local syntax_fail=0
    for sub in "${subsystems[@]}"; do
        if "${PYTHON}" -c "import py_compile; py_compile.compile('${SCRIPT_DIR}/${sub}', doraise=True)" 2>>"${DEPLOY_LOG}"; then
            syntax_ok=$((syntax_ok + 1))
        else
            log FAIL "Syntax error in: ${sub}"
            syntax_fail=$((syntax_fail + 1))
        fi
    done
    log OK "Syntax check: ${syntax_ok}/${#subsystems[@]} passed"

    if [[ ${syntax_fail} -gt 0 ]]; then
        log FAIL "${syntax_fail} file(s) have syntax errors — fix before launching"
        return 1
    fi

    # Show launch readiness (don't auto-start — operator decides)
    echo ""
    echo -e "  ${CYAN}${BOLD}┌─────────────────────────────────────────────────┐${NC}"
    echo -e "  ${CYAN}${BOLD}│  WATCHDOG LAUNCH COMMAND:                       │${NC}"
    echo -e "  ${CYAN}${BOLD}│                                                 │${NC}"
    echo -e "  ${CYAN}${BOLD}│${NC}  ${WHITE}nohup ${PYTHON} watchdog_monitor.py &${NC}             ${CYAN}${BOLD}│${NC}"
    echo -e "  ${CYAN}${BOLD}│                                                 │${NC}"
    echo -e "  ${CYAN}${BOLD}│  ${DIM}Watchdog auto-starts all 6 subsystems${NC}        ${CYAN}${BOLD}│${NC}"
    echo -e "  ${CYAN}${BOLD}│  ${DIM}+ Daily Scanner via cron at 00:05 UTC${NC}        ${CYAN}${BOLD}│${NC}"
    echo -e "  ${CYAN}${BOLD}└─────────────────────────────────────────────────┘${NC}"
}

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 5: HEALTH CHECK
# ═══════════════════════════════════════════════════════════════════════════════
phase_healthcheck() {
    log STEP "PHASE 5/5 — HEALTH CHECK"

    # Run the Python health check assistant
    log INFO "Running vps_env_setup.py health diagnostics..."
    echo ""

    "${PYTHON}" "${SCRIPT_DIR}/vps_env_setup.py" --health-check 2>>"${DEPLOY_LOG}"
    local hc_exit=$?

    if [[ ${hc_exit} -eq 0 ]]; then
        log OK "All health checks passed"
    else
        log FAIL "Health check returned exit code ${hc_exit}"
        return 1
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# FINAL REPORT
# ═══════════════════════════════════════════════════════════════════════════════
final_report() {
    echo ""
    echo -e "${GREEN}${BOLD}"
    cat << 'REPORT'
    ╔═══════════════════════════════════════════════════════════════╗
    ║                                                               ║
    ║     ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗    ║
    ║     ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║    ║
    ║     ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║    ║
    ║     ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║    ║
    ║     ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║    ║
    ║     ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝    ║
    ║                                                               ║
    ║          O P E R A T I O N A L                                ║
    ║                                                               ║
    ╚═══════════════════════════════════════════════════════════════╝
REPORT
    echo -e "${NC}"
    echo -e "  ${GREEN}${BOLD}SYSTEM OPERATIONAL — BY ФорексГод${NC}"
    echo -e "  ${GREEN}${BOLD}READY FOR LIVE TRADING${NC}"
    echo ""
    echo -e "  ${DIM}Glitch in Matrix V8.0 · VPS-Ready Edition${NC}"
    echo -e "  ${DIM}Deploy log: ${DEPLOY_LOG}${NC}"
    echo -e "  ${DIM}$(date -u '+%Y-%m-%d %H:%M:%S UTC')${NC}"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
# MAIN EXECUTION
# ═══════════════════════════════════════════════════════════════════════════════
main() {
    cd "${SCRIPT_DIR}"

    banner

    local start_time
    start_time=$(date +%s)

    phase_environment
    phase_filesystem
    phase_timezone
    phase_watchdog
    phase_healthcheck

    local end_time
    end_time=$(date +%s)
    local elapsed=$((end_time - start_time))

    echo ""
    log OK "Deployment completed in ${elapsed}s"

    final_report
}

main "$@"
