from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class SwingPoint:
    index: int
    price: float
    swing_type: str  # 'high' or 'low'
    candle_time: datetime


@dataclass
class CHoCH:
    index: int
    direction: str
    break_price: float
    previous_trend: str
    candle_time: datetime
    swing_broken: SwingPoint
 

@dataclass
class BOS:
    index: int
    direction: str
    break_price: float
    candle_time: datetime
    swing_broken: SwingPoint


@dataclass
class FVG:
    index: int
    direction: str
    top: float
    bottom: float
    middle: float
    candle_time: datetime
    is_filled: bool = False
    associated_choch: Optional[CHoCH] = None
    quality_score: int = 0
    is_momentum_entry: bool = False  # 🔥 V8.0: True for MOMENTUM_CONTINUATION (3+ BOS, no pullback FVG)


@dataclass
class OrderBlock:
    """📦 Order Block - Ultima lumânare opusă înainte de impuls instituțional (CHoCH)"""
    index: int
    direction: str  # 'bullish' or 'bearish'
    top: float  # Body high pentru bullish, wick high pentru bearish
    bottom: float  # Wick low pentru bullish, body low pentru bearish
    middle: float
    candle_time: datetime
    associated_choch: Optional[CHoCH] = None
    associated_fvg: Optional[FVG] = None  # FVG lăsat de impuls
    has_unfilled_fvg: bool = False  # TRUE = Setup 10/10 (OB + FVG necompletat)
    ob_score: int = 0  # 1-10 scoring (10 = OB + unfilled FVG)
    impulse_strength: float = 0.0  # Mărimea impulsului după OB (în pips/pct)


# V40.1 — crypto/metals: tavan macro = max body-high pe fereastra D1 (nu LH local post-crash)
CRYPTO_MACRO_CEILING_LOOKBACK = 150
CRYPTO_MACRO_CEILING_MIN_BARS = 90


@dataclass
class StructuralRangeState:
    """V40 / V40.1 — macro trading range (LH major / LL major), all pairs."""
    macro_range_high: float
    macro_range_low: float
    macro_range_high_bar: int
    macro_range_low_bar: int
    locked: bool
    locked_bias: str  # 'bearish' | 'bullish' | 'neutral'


@dataclass
class ActiveDealingRange:
    """V43.0 — live dealing range post-leg (stateless; JSON persistence is Etapa 2)."""
    container_low: float
    container_high: float
    current_swing_high: float   # LH (bearish) / HH (bullish)
    current_swing_low: float    # LL (bearish) / HL (bullish)
    last_lh: float
    last_hl: float
    last_ll: float
    current_swing_high_bar: int
    current_swing_low_bar: int
    leg_anchor_index: int
    price_inside: bool


@dataclass
class POIResolution:
    """V43.0 — passive POI outcome for scanner/radar (no JSON writes here)."""
    fvg: Optional['FVG']
    adr: Optional[ActiveDealingRange]
    preserve_stored_poi: bool = False
    poi_source: str = 'detect_fvg'
    poi_zombie: bool = False
    adr_rescan: bool = False
    rejected_poi_top: Optional[float] = None
    rejected_poi_bottom: Optional[float] = None


@dataclass
class D1AuthContext:
    """V67 B: Single D1 authority snapshot per symbol per scan run.

    Canonical replacement for legacy ``determine_daily_trend`` and
    ``infer_d1_strategy_type`` — built exclusively via ``build_d1_context()``.
    """
    symbol: str
    trend: str
    strategy_type: str
    macro_swings: str
    direction: str
    d1_bias_direction: str
    daily_bias: str
    latest_signal: Optional[object]
    leg_choch: Optional['CHoCH']
    d1_signal_type: str
    chochs: List['CHoCH']
    bos_list: List
    range_state: Optional[StructuralRangeState]
    swing_h: List['SwingPoint']
    swing_l: List['SwingPoint']

    def as_dict(self) -> dict:
        return {
            'trend': self.trend,
            'strategy_type': self.strategy_type,
            'macro_swings': self.macro_swings,
            'direction': self.direction,
            'd1_bias_direction': self.d1_bias_direction,
            'daily_bias': self.daily_bias,
            'latest_signal': self.latest_signal,
            'leg_choch': self.leg_choch,
            'd1_signal_type': self.d1_signal_type,
        }


@dataclass
class TradeSetup:
    symbol: str
    daily_choch: CHoCH
    fvg: FVG  # Daily FVG (D1 POI zone)
    h4_choch: Optional[CHoCH]
    order_block: Optional['OrderBlock'] = None  # 📦 V3.5: Order Block pentru entry precision
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    risk_reward: float = 0.0
    estimated_rr: float = 0.0  # 🎯 V3.5: RR estimat pentru swing (minimum 1:5)
    setup_time: datetime = None
    priority: int = 0
    strategy_type: str = "reversal"  # D1 bias: 'reversal' or 'continuation'
    status: str = 'MONITORING'
    # V10.4: 4H Sync FVG — the FVG generated by the 4H confirmation move (entry zone)
    h4_sync_fvg: Optional[FVG] = None
    h4_sync_fvg_top: float = 0.0
    h4_sync_fvg_bottom: float = 0.0
    # V24.6 PERMISSIVE DAILY FLOW: True = FVG corp absent/mituit — setup validat NUMAI prin
    # structura Daily (CHoCH/BOS). Radarul 4H este arbitrul final — NU se execută fără 4H CHoCH!
    daily_bias_active: bool = False
    confidence: str = 'NORMAL'  # V40.3: LOW_W1_COUNTER_TREND when D1 vs W1 macro conflict
    w1_bias: Optional[str] = None
    w1_poi_top: Optional[float] = None
    w1_poi_bottom: Optional[float] = None
    w_d_aligned: bool = True
    structural_breach: bool = False  # V43.0 E1-T7 — close broke LH (SHORT) or LL (LONG); passive signal
    adr_lh: Optional[float] = None
    adr_ll: Optional[float] = None
    adr_hl: Optional[float] = None
    poi_v43_source: Optional[str] = None
    preserve_stored_poi: bool = False
    d1_bias_direction: Optional[str] = None  # V63 canonical trend
    d1_signal_type: Optional[str] = None  # V63: CHoCH or BOS
